In [1]:
import torch

In [37]:
a = torch.ones((2, 3, 3))
a[:, 1, :] *=2
a[:, 2, :] *=3
print(a)
b = 2 * torch.clone(a)
print('\n')
print(b)
print(a.shape, b.shape)

tensor([[[1., 1., 1.],
         [2., 2., 2.],
         [3., 3., 3.]],

        [[1., 1., 1.],
         [2., 2., 2.],
         [3., 3., 3.]]])


tensor([[[2., 2., 2.],
         [4., 4., 4.],
         [6., 6., 6.]],

        [[2., 2., 2.],
         [4., 4., 4.],
         [6., 6., 6.]]])
torch.Size([2, 3, 3]) torch.Size([2, 3, 3])


In [47]:
c = torch.cat((torch.transpose(a, 1, 2)[0], b[0]), 0)
print(c.shape)
print('\n'*5)
print(c)

torch.Size([5, 3])






tensor([[1., 1., 1.],
        [1., 1., 1.],
        [2., 2., 2.],
        [4., 4., 4.],
        [6., 6., 6.]])


In [10]:
a.view(-1, 3, 8)

tensor([[[1., 1., 1., 1., 2., 2., 2., 2.],
         [3., 3., 3., 3., 1., 1., 1., 1.],
         [2., 2., 2., 2., 3., 3., 3., 3.]]])