In [1]:
import torch

In [11]:
a = torch.ones((2, 3, 4))
a[:, 1, :] *=2
a[:, 2, :] *=3
print(a)
print(a.shape)
print('-'*20)
a = torch.cat((a[0], a[1]), 1)
print(a)
a.shape

tensor([[[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.]],

        [[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.]]])
torch.Size([2, 3, 4])
--------------------
tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3., 3., 3.]])


torch.Size([3, 8])

In [7]:
a = torch.ones((2, 3, 4))
print(a, a.shape)
print('-'*20)
scaling_factors = torch.tensor([1, 2, 3]).view(1, 3, 1)
print(scaling_factors, scaling_factors.shape)
print('-'*20)
a *= scaling_factors
print(a)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]) torch.Size([2, 3, 4])
--------------------
tensor([[[1],
         [2],
         [3]]]) torch.Size([1, 3, 1])
--------------------
tensor([[[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.]],

        [[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.]]])


In [10]:
a.view(-1, 3, 8)

tensor([[[1., 1., 1., 1., 2., 2., 2., 2.],
         [3., 3., 3., 3., 1., 1., 1., 1.],
         [2., 2., 2., 2., 3., 3., 3., 3.]]])