<a href="https://colab.research.google.com/github/maxtost10/Playground-vs/blob/main/Vector_dimensions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import torch

In [ ]:
x = pd.DataFrame()

In [ ]:
x['timestep1'] = [1, 4, 7]
x['timestep2'] = [2, 5, 8]
x['timestep3'] = [3, 6, 9]
x['timestep4'] = [4, 7, 10]
x['value1'] = [101, 104, 107]
x['value2'] = [102, 105, 108]
x['value3'] = [103, 106, 109]
x['value4'] = [104, 107, 110]

In [ ]:
x.shape, x.keys()

((3, 8),
 Index(['timestep1', 'timestep2', 'timestep3', 'timestep4', 'value1', 'value2',
        'value3', 'value4'],
       dtype='object'))

# Pandas Concatenate

In [ ]:
pd_concat_axis1 = pd.concat([x[['timestep1', 'timestep2']], x[['value1', 'value2']]], axis=1)
print(pd_concat_axis1)

   timestep1  timestep2  value1  value2
0          1          2     101     102
1          4          5     104     105
2          7          8     107     108


In [ ]:
pd_concat_axis0 = pd.concat([x[['timestep1', 'timestep2']], x[['value1', 'value2']]], axis=0)
print(pd_concat_axis0)

   timestep1  timestep2  value1  value2
0        1.0        2.0     NaN     NaN
1        4.0        5.0     NaN     NaN
2        7.0        8.0     NaN     NaN
0        NaN        NaN   101.0   102.0
1        NaN        NaN   104.0   105.0
2        NaN        NaN   107.0   108.0


In [ ]:
a = x[[col for col in x.columns if col.startswith('time')]].values # Zwei Eckige Klammern wichtig
b = x[[col for col in x.columns if col.startswith('value')]].values # .values gibt array
a, b

(array([[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 7,  8,  9, 10]]),
 array([[101, 102, 103, 104],
        [104, 105, 106, 107],
        [107, 108, 109, 110]]))

# Numpy Concatenate und Stack

In [ ]:
cat_0 = np.concatenate([a, b], axis=0)
cat_0

array([[  1,   2,   3,   4],
       [  4,   5,   6,   7],
       [  7,   8,   9,  10],
       [101, 102, 103, 104],
       [104, 105, 106, 107],
       [107, 108, 109, 110]])

In [ ]:
cat_0 = np.concatenate([a, b], axis=1)
cat_0

array([[  1,   2,   3,   4, 101, 102, 103, 104],
       [  4,   5,   6,   7, 104, 105, 106, 107],
       [  7,   8,   9,  10, 107, 108, 109, 110]])

In [ ]:
print('This does not work :(')
cat_0 = np.concatenate([a, b], axis=2)

This does not work :(


AxisError: axis 2 is out of bounds for array of dimension 2

In [ ]:
stack_0 = np.stack([a, b], axis=0)
print('Stacking on axis 0')
stack_0

Stacking on axis 0


array([[[  1,   2,   3,   4],
        [  4,   5,   6,   7],
        [  7,   8,   9,  10]],

       [[101, 102, 103, 104],
        [104, 105, 106, 107],
        [107, 108, 109, 110]]])

In [ ]:
stack_1 = np.stack([a, b], axis=1)
print('Stacking on axis 1')
stack_1

Stacking on axis 1


array([[[  1,   2,   3,   4],
        [101, 102, 103, 104]],

       [[  4,   5,   6,   7],
        [104, 105, 106, 107]],

       [[  7,   8,   9,  10],
        [107, 108, 109, 110]]])

In [ ]:
stack_2 = np.stack([a, b], axis=2)
print('Stacking on axis 2')
print(stack_2)
print(stack_2.shape)

Stacking on axis 2
[[[  1 101]
  [  2 102]
  [  3 103]
  [  4 104]]

 [[  4 104]
  [  5 105]
  [  6 106]
  [  7 107]]

 [[  7 107]
  [  8 108]
  [  9 109]
  [ 10 110]]]
(3, 4, 2)


# Last but not least: Torch

In [ ]:
# Konvertiere zu Tensors
a_t = torch.tensor(a)
b_t = torch.tensor(b)

print("a_t.shape", a_t.shape)
print(a_t)
print("b_t.shape", b_t.shape)
print(b_t)


a_t.shape torch.Size([3, 4])
tensor([[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 7,  8,  9, 10]])
b_t.shape torch.Size([3, 4])
tensor([[101, 102, 103, 104],
        [104, 105, 106, 107],
        [107, 108, 109, 110]])


In [ ]:
cat_t0 = torch.cat([a_t, b_t], dim=0)
cat_t1 = torch.cat([a_t, b_t], dim=1)
print("torch.cat dim=0", cat_t0.shape)
print(cat_t0)
print("torch.cat dim=1", cat_t1.shape)
print(cat_t1)

torch.cat dim=0 torch.Size([6, 4])
tensor([[  1,   2,   3,   4],
        [  4,   5,   6,   7],
        [  7,   8,   9,  10],
        [101, 102, 103, 104],
        [104, 105, 106, 107],
        [107, 108, 109, 110]])
torch.cat dim=1 torch.Size([3, 8])
tensor([[  1,   2,   3,   4, 101, 102, 103, 104],
        [  4,   5,   6,   7, 104, 105, 106, 107],
        [  7,   8,   9,  10, 107, 108, 109, 110]])


In [ ]:
stack_t0 = torch.stack([a_t, b_t], dim=0)
stack_t1 = torch.stack([a_t, b_t], dim=1)
stack_t2 = torch.stack([a_t, b_t], dim=2)
print("torch.stack dim=0", stack_t0.shape)
print(stack_t0)
print("torch.stack dim=1", stack_t1.shape)
print(stack_t1)
print("torch.stack dim=2", stack_t2.shape)
print(stack_t2)

torch.stack dim=0 torch.Size([2, 3, 4])
tensor([[[  1,   2,   3,   4],
         [  4,   5,   6,   7],
         [  7,   8,   9,  10]],

        [[101, 102, 103, 104],
         [104, 105, 106, 107],
         [107, 108, 109, 110]]])
torch.stack dim=1 torch.Size([3, 2, 4])
tensor([[[  1,   2,   3,   4],
         [101, 102, 103, 104]],

        [[  4,   5,   6,   7],
         [104, 105, 106, 107]],

        [[  7,   8,   9,  10],
         [107, 108, 109, 110]]])
torch.stack dim=2 torch.Size([3, 4, 2])
tensor([[[  1, 101],
         [  2, 102],
         [  3, 103],
         [  4, 104]],

        [[  4, 104],
         [  5, 105],
         [  6, 106],
         [  7, 107]],

        [[  7, 107],
         [  8, 108],
         [  9, 109],
         [ 10, 110]]])
